- hosts: vault
  tasks:
    - name: Change hostname to vault
      command: hostnamectl set-hostname vault
      become: yes

    - name: Edit hostname to /etc/hostname
      lineinfile:
        dest: /etc/hostname
        regexp: '^ip*'
        line: 'vault'
        state: present
      become: yes

    - name: Add hostname to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost vault'
        state: present
      become: yes

    - name: Install unzip
      apt:
        name: unzip
        state: latest
        update_cache: true
      become: yes

    - name: Install Vault binary
      unarchive:
        src: https://releases.hashicorp.com/vault/1.11.0/vault_1.11.0_linux_arm64.zip?_ga=2.46861604.266934807.1656688916-601040367.1656688916&_gl=1*1s5r6o3*_ga*NjAxMDQwMzY3LjE2NTY2ODg5MTY.*_ga_P7S46ZYEKW*MTY1NjY4ODkxNS4xLjEuMTY1NjY4OTYyNS4w
        dest: /usr/local/bin/
        remote_src: yes
      become: yes

    - name: Create Vault Log directory
      file:
        path: /var/log/vault
        state: directory
      become: yes

    - name: Create Vault Data directory
      file:
        path: /var/lib/vault/data
        state: directory
      become: yes

    - name: Create a Vault Log symbolic link 
      file:
        src: /var/log/vault/
        dest: /var/lib/vault/logs
        owner: root
        group: root
        state: link
      become: yes

    - name: Create Vault Config directory
      file:
        path: /etc/vault
        state: directory
      become: yes


    - name: Create config file
      file:
        path: /etc/vault/config.json
      become: yes

    - name: Create Vault User
      user:
        name: vault
        group: vault
        system: true
    
    - name: '[/var/lib/vault] Change permissions to Vault User' 
      file:
        path: /var/lib/vault
        state: directory
        recurse: yes
        owner: vault
        group: vault

    - name: '[/etc/vault] Change permissions to Vault User'
      file:
        path: /etc/vault
        state: directory
        recurse: yes
        owner: vault
        group: vault

    - name: '[/var/log/vault] Change permissions to Vault User'
      file:
        path: /var/log/vault
        state: directory
        recurse: yes
        owner: vault
        group: vault

    - name: Writing Vault Configuration file
      copy:
        dest: /etc/vault/config.json
        content: |
          storage "file" {
            path = "/var/lib/vault/data"
          }

          listener "tcp" {
            address     = "0.0.0.0:8200"
            tls_disable = 1
          }
      
    - name: Writing Vault Service file
      copy:
        dest: /etc/systemd/system/vault.service
        content: |
          [Unit]
          Description = Vault Server
          Requires = network-online.target
          After = network-online.target
          ConditionFileNotEmpty = /etc/vault/config.json

          [Service]
          User = vault
          Group = vault
          Restart = on-failure
          ExecStart = /usr/local/bin/vault server -config=/etc/vault/config.json
          StandardOutput = /var/log/vault/output.log
          StandardError = /var/log/vault/error.log
          ExecReload = /bin/kill -HUP $MAINPID
          KillSignal = SIGTERM

          [Install]
          WantedBy = multi-user.target

    - name: Enabling Vault Service
      systemd:
        name: vault.service
        enabled: yes
        masked: no

    - name: Starting Vault Service
      systemd:
        name: vault.service
        state: started
        enabled: yes
